language: python
python: "2.7"
matrix:
  include:
    - install:
      - pip install tox
      python:
        - "2.7"
      script: tox -e django111
      env:
        name: Python 2.7, Django 1.11 Unit Tests
    - python: 3.5
      install: 
        - pip install tox
      script: tox -e py35-django111
      env:
        name: Python 3.5, Django 1.11 Unit Tests
